### ISSUE TITLE
Source Code Documentation

### ISSUE THREAD

**Issue by byterazor** [glentner/CLI#1]
Hi,

I really would like to use this framework and even extend it because it is similar to the Perl MooseX::App framework. Still there is no source code documentation at all. :(

**Comment by glentner** [comment]
Wow. Sorry for that late reply (almost a year). I haven't been watching this repository much and didn't notice that there was an issue. Did you the demos in the examples directory? Indeed,  documentation that just lays out what all the types are and how to retrieve values and an overview of how to deal with composite CLI's (here MultiMode) is needed.

I'm planning a complete refactor of this library and the documentation will be included this time. I need this as a dependency for a few other projects I'm working on right now.

**Comment by lefperuch** [comment]
Hello,

Do you still intend to do a refactor of this project? I've found this by looking for some framework to implement cli applications in C++ and I have interest in helping you if you need.

Please let me know if you are still planning on releasing a new version of this code.

**Comment by glentner** [comment]
@lefperuch Yes, I still want to keep this thing alive. I built this whole thing over the course of about a week because I myself needed it. I haven't spent any time in C++ recently. There are a bunch of things in the code that could be done better (e.g., the `Register()` calls could actually be done automatically). If you have the experience and could help maintain and document I would definitely support that.

**Comment by glentner** [comment]
@lefperuch To you question, it could be some time before a refactor happens.
